### ISSUE TITLE
Decimal Value For Delay In generators.yml

### ISSUE THREAD

**Issue by TheSkilledCat** [andrei1058/BedWars1058#247]
I want to make a config so that some arenas have different spawning rate like hypixel.

```
Default:
  iron:
    delay: 0.33
    amount: 1
    spawn-limit: 48
```
I'm pretty sure that this values won't work and still spawn 1 iron ingot per second.
So I hope you could make it so we could set a value like this and get more than 1 ingot per second

Thank You and I hope this would be added :........)
