### ISSUE TITLE
New options and improvements to fireballs and tnt jump

### ISSUE THREAD

**Issue by samupro-dev** [andrei1058/BedWars1058#266]
**Is your feature request related to a problem? Please describe.**
Add new options for tnt jump and fireball and improve a how the `tnt-jumps-settings` category is displayed

**Describe the solution you'd like**
Hi, it would be very nice and useful to add these new options in the `config.yml` under the `tnt-jump-settings` category:
* explosion-size: NUMBER
* make-fire: BOOLEAN
* and arrange the damage section in:
```yaml
  damage:
    self: NUMBER
    enemy: NUMBER
    teammates: NUMBER
    fall: NUMBER (how much damage is lost on impact with the ground) [NEW]
```
Then there would also be to fix the knockback that gives because many times it moves you to the right or to the left. As far as fireballs are concerned, everything is fine but even here the `fall` option should be added in the `damage` section.
Maybe it would be even better to change the name from `tnt-jump-settings` to `tnt-jump`

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing
