### ISSUE TITLE
Disabled Worlds.

### ISSUE THREAD

**Issue by xmyoard** [andrei1058/BedWars1058#34]
please add a Disabled Worlds. feature.
because the server hosting like aternos or any big host with a spigot installed needs it, so when we do /bw setlobby it shd work only on that world, because in spigot servers when we go to survival the bedwars items like map selector are coming in survival worlds which is bad. and this is a big feature needed by people/servers using spigot or any other software without a network connection between them.

**Comment by xmyoard** [comment]
example config:
```yml

#Where the Lobby Items should come.
Lobby-World:
- "lobby"
- "lobby2"

#Do not touch this, this is done automatically when an arena gets created.
bedwars-worlds:
- "bedwars1"
- "bedwars2"
```
this is just an example, I think you got what I meant. 
and the bedwars worlds gets filled up automatically by when creating an arena
this feature for servers has 2 game modes on the same server.
