### ISSUE TITLE
Netherite armor equip bug

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#657]
**Describe the bug**

Adding netherite armor to the shop and buying it equips them in the wrong spot
**To Reproduce**

1. Create a weight 3 netherite armor in the shop
```    
    netherite-armor:
      content-settings:
        content-slot: 22
        is-permanent: true
        is-downgradable: false
        weight: 3
      content-tiers:
        tier1:
          tier-item:
            material: NETHERITE_BOOTS
            data: 0
            amount: 1
            enchanted: false
          tier-settings:
            cost: 12
            currency: emerald
          buy-items:
            boots:
              material: NETHERITE_BOOTS
              data: 0
              amount: 1
              auto-equip: true
            leggings:
              material: NETHERITE_LEGGINGS
              data: 0
              amount: 1
              auto-equip: true
```
2. Buy armor in-game
3. See netherite leggings in the wrong spot (boots)

**Expected behavior**

Like buying diamond armor, I should have netherite leggings and netherite boots in the correct spot.
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216910561-964bf6c7-2957-406b-9abd-da928f66e293.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur
 - Server Version: 1.19.3
 - Plugin Version: 23.2

**Additional context**
